permalink: pretty
markdown: kramdown
repository: 2factorauth/twofactorauth
env: development
exclude:
  - vendor/
  - Gemfile.lock
  - Gemfile
  - .*
  - entries/
  - scripts/
  - tests/
  - schema.json
  - service-worker.js
  - manifest.json
  - README.md
theme_color: green
