version: 2.1
jobs:
  tests:
    docker:
      - image: ruby:latest
    steps:
      - checkout

      - restore_cache:
          keys:
            - alexa-cache

      - run:
          name: Check Alexa ranking
          command: ./tests/alexa.rb

      - save_cache:
          key: alexa-cache
          paths:
            - "/tmp/alexa/*"

      - run:
          name: Check Twitter handles
          command: |
            gem install twitter
            ./tests/twitter.rb

      - run:
          name: Check Facebook handles
          command: ./tests/facebook.rb

workflows:
  version: 2
  workflow:
    jobs:
      - tests
