blank_issues_enabled: false
contact_links:
  - name: 🚨 Report a code of conduct violation
    url: .github/CODE_OF_CONDUCT.md#enforcement
    about: Review the enforcement section of our code of conduct to report a violation.
