name: Deploy to GitHub Pages

on:
  push:
    branches: "4.0"

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'carlgo11/twofactorauth'

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: vendor/cache
          key: ${{ runner.os }}-bundle-${{ hashFiles('**/Gemfile.lock') }}

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install dependencies
        run: |
          bundle config set path 'vendor/cache'
          bundle config set cache_all true
          bundle install --jobs 4 --retry 3
          [ -d "vendor/cache" ] || { bundle package; }

      - name: Import PGP key
        id: pgp
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.pgp_key }}
          passphrase: ${{ secrets.pgp_passphrase }}

      - name: Generate API files
        run: |
          ./scripts/create-api.sh
          ./scripts/APIv1.rb
          ./scripts/APIv2.rb
          ./scripts/APIv3.rb
          ./scripts/sign.sh ${{ secrets.pgp_passphrase }} ${{ steps.pgp.outputs.keyid }}

      - name: Build the site
        run: bundle exec jekyll build --config _config.yml

      - name: Deploy to GH Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: _site
          fqdn: ${{ secrets.domain }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}